### ISSUE TITLE
Soulsvision CTD

### ISSUE THREAD

**Issue by 69Godless** [samjviana/souls_vision#13]
Posting here as suggested, about everything above 0.3.3 ending in CTD.

So I used your final 0.5.1. and CTD'd again. Log attached. I'm also attaching the log of the working 0.3.3 for comparison, that's the second one.

I use Win 10 22h2, Ryzen 3 1200, Nvidia GTX1060 3 GB with a 566.14 WHQL driver installed. The Elden Ring version is 1.12  with DLC Shadow of the Erdtree. No Afterburner or RTSS, it makes it crash, same as the Posture bar mod.

I'm also sending the pic of all the mods installed.

If anything else is needed, I'm happy to provide the info.

![SoulsvisionWEshot](https://github.com/user-attachments/assets/99592adc-85ce-4d1a-99c1-a04f15028089)
[souls_vision.log](https://github.com/user-attachments/files/18402413/souls_vision.log)
[souls_vision.log](https://github.com/user-attachments/files/18402425/souls_vision.log)

**Comment by samjviana** [comment]
thank you for the info, this was happening to a lot of people ...
after reinstalling elden ring the crash started happening for me as well, which is good since i was able to test things ... and i think i fixed it in the latest [commit](https://github.com/samjviana/souls_vision/commit/2d3324a9d5a22c782e4f5f911cc442e38f4f131c) which is related to the [0.5.3 version](https://github.com/samjviana/souls_vision/releases/tag/0.5.3).
you can download it only from here at this point, as nexus is incorrectly quarantining the file (i'm trying to address this with someone from nexus)
tell me if this fixes the problem for u so i can close this afterwards

**Comment by 69Godless** [comment]
No. It still crashes on Bandai logo or even earlier. Here's the log.
I should probably mention my copy is not an original.

[souls_vision053.log](https://github.com/user-attachments/files/18442193/souls_vision053.log)

**Comment by samjviana** [comment]
can you try [0.5.4](https://github.com/samjviana/souls_vision/releases/tag/0.5.4) just added more verifications

**Comment by 69Godless** [comment]
Same.

[souls_vision054.log](https://github.com/user-attachments/files/18443035/souls_vision054.log)

**Comment by samjviana** [comment]
try [this one](https://github.com/samjviana/souls_vision/releases/tag/0.5.4-exp-1) now, it should add a considerable amount of logs that will allow me to know at which point the code is crashing, also ... try adding a delay (using the `delay` option, something between 1 and 10 seconds should do the trick, the parameters is in milliseconds)
hopefully i'm not bothering too much with those tests

**Comment by 69Godless** [comment]
Where do I enable the delay?

**Comment by samjviana** [comment]
in the `souls_vision.toml` there should be a `delay` parameter, you just have to edit it

**Comment by 69Godless** [comment]
This one is hit and miss. 5 tries, two succesful loads, three CTD's. At least this time From software logo and even the initial game screen loads (10s), but still crashes. The 5s loaded, the second time crashed. The 6s crashed then loaded. The 10s crashed. The log is with 10s delay enabled.

[souls_vision.log](https://github.com/user-attachments/files/18443526/souls_vision.log)

**Comment by samjviana** [comment]
is this the 0.5.4-exp-1? i expected to see some additional info in the log

**Comment by 69Godless** [comment]
Yep

**Comment by samjviana** [comment]
:/ 
either way, you saying that this time it worked 2/5 times is a good thing, meaning i know what to explore

**Comment by 69Godless** [comment]
Glad to help, it's a great mod, suuuper helpful. Let me know if you need more assist.

**Comment by 69Godless** [comment]
I thought the log length had something to do with the game not loading. So I went back to 5s, the game loaded and now the log is more populated.

[souls_vision.log](https://github.com/user-attachments/files/18443834/souls_vision.log)

**Comment by samjviana** [comment]
that was what i expected, but i a "crashed" scenario, also ... don't use the exp-1 version in a "definitive" manner
those logs are "infinite" and can affect performace, i released it just for experiment 

one question that came to mind, how do u disable the anti-cheat? like which method used?

**Comment by 69Godless** [comment]
I didn't. I told you it's not an original copy. Playing offline.

**Comment by samjviana** [comment]
oh okay, when u said 1.12 i thought it was a downgrade. this adds more depth to the problem, as those versions usually have intrinsic things altered in the game's binary to bypass the usual checks.
i'll keep working on making it stable and keep u posted ... but i wanted to highlight that a "not original copy" is unpredictable.

**Comment by samjviana** [comment]
also ... adding a mod to skip the splash screens (the bandai namco and the from software logos) can help with stability. (i'll add this note/recommendation to the mod's description)

**Comment by 69Godless** [comment]
Ah, okay. I got you wrong then, sorry.

**Comment by samjviana** [comment]
no problem 😁
the information u shared helped a lot anyway, thx
let me know if the "skip splash screen" thing improves your experience

**Comment by 69Godless** [comment]
Will do. I can always use the 0.3.3. anyway if it doesn't work out.

**Comment by 69Godless** [comment]
Well, I tried the Skip splash mod but it didn't help with 0.5.4 

So I'll be using the 0.3.3, no problems with that one.

**Comment by Scotomas** [comment]
hey could you explain how the 0.3.3 version of this mod works for you? I understand that it has the "sv_assets", but I got the same result as the latest version (only tried it once dropped both the dll and sv_assets folder in mods folder) 

I've been following this thread to try get this mod to work for me. I'm only using the seamless coop mod and the latest version of this mod (0.5.4) 

after setting the delay to 5 in the sv_vision.toml file, it works like 30/70 of the time with it mostly crashing between the Bandi Namco logo and the Elden Ring main menu.

I tried talking to someone on discord who got it to work with the convergence mod. I think he was using this mod "Lazy Loader" by Church Guard. Originally for DS3, but it works on other souls games. it was made to "Load many dlls that would otherwise conflict."

I couldn't get that to work, but maybe there is something there to help out. I by all means can not code a mod

Thank you guys for looking into this

Link to Lazy Loader: https://www.nexusmods.com/darksouls3/mods/677

Config for Lazy Loader:

((

;LazyLoad by Church Guard

; NOTE: THIS METHOD DOES NOT WORK FOR ALL DLL MODS!!!
;       IF YOU ARE CRASHING OR MODS ARE NOT WORKING THAT MEANS
;       ONE OF THE MODS MUST BE PROPERLY LOADED IN [CHAINLOAD].
;       THERE CAN ONLY BE ONE PROPERLY LOADED MOD AT A TIME

; Define the folder containing dll files to be lazy loaded.
[LAZYLOAD]
dllModFolderName=dllMods

; To load another dll that reqires it be dinput8.dll, simply rename the
; other dll file, place it the same folder as this and enter its name below
; Depending on what the other dll does this may not work, but usually does
; example: dll = wexdust.dll
[CHAINLOAD]
dll= convergence_dlinput8.dll

; To load another dll that reqires it be dinput8.dll, simply rename the
; other dll file, place it the same folder as this and enter its name below
; Depending on what the other dll does this may not work, but usually does
; example: dll = wexdust.dll
[CHAINLOAD]
dll= 

))

**Comment by 69Godless** [comment]
Well I wouldn't know, it just does. Did you clear all the files from the previous version? Did a restart? I remember Posture bar mode was quirky like that, needed to restart Windows to make it work between versions. Try changing between Fullscreen or Borderless, but to me it works both ways.

**Comment by Scotomas** [comment]
@69Godless I'll give it another try and ill try to include restarting my system and playing with the ingame settings.

are you putting the sv_assets folder in the mods folder with your dlls?

**Comment by 69Godless** [comment]
Yes, then after the first run two more files are created along with the souls_vision.dll and sv_assets folder in the mods folder, souls_vision.log and sv_config.json.

**Comment by samjviana** [comment]
as of 0.4.0, the `sv_assets` folder is no longer required, as the resources are bundled into the .dll.  
starting from 0.5.0, the config is managed in `souls_vision.toml` instead of json.

it's good to know that a higher delay seems to lower the crash rate. this helps me determine what and where to explore in order to fix it. thx.

**Comment by samjviana** [comment]
I'll be closing this and centering all "Crash at startup" problems in a primary issue, please refer to #17
