### ISSUE TITLE
Startup CTD

### ISSUE THREAD

**Issue by Teacyn** [samjviana/souls_vision#14]
Saw you were looking for proper reports, so here's mine.

Crash happens 3-10 seconds after launching, before control is gained.

Mod version: 0.5.1 (Latest at time of post. For context every version has crashed for me)
Loading via Mod Engine 2
Other mods being used: Elden Ring Reforged, Transmogrify Armor (included in ERR), Alt Saves (included in ERR), ermaterialparamexposer (included in ERR), Scripts-Data-Exposer-FS (included in ERR), UltrawideFix (included in ERR)
No overlays in use (steam overlay included)
AMD GPU

[souls_vision.log](https://github.com/user-attachments/files/18431807/souls_vision.log)

sv_config.toml: 
![image](https://github.com/user-attachments/assets/6d2683ab-0250-4a57-81c9-0397959bd771)

**Comment by samjviana** [comment]
thank you for all the information, i ended up reinstalling elden ring and got to replicate the crash, i fixed it in the latest [commit](https://github.com/samjviana/souls_vision/commit/2d3324a9d5a22c782e4f5f911cc442e38f4f131c) which is related to the [0.5.3 version](https://github.com/samjviana/souls_vision/releases/tag/0.5.3).
you can download it only from here at this point, as nexus is incorrectly quarantining the file (i'm trying to address this with someone from nexus)
update me if this works just for me to close this issue

**Comment by Teacyn** [comment]
No dice, still crashing with 0.5.3. Same setup and circumstances. If I increase the Delay value, the crash happens later but it seems to happen without fail once the mod tries to initialize. 

[souls_vision.log](https://github.com/user-attachments/files/18446175/souls_vision.log)

![Image](https://github.com/user-attachments/assets/b48eea52-95c0-4b30-949b-9991d4890cb4)

**Comment by samjviana** [comment]
can you try 0.5.4?? it's a little bit more robust than 0.5.3 ...
also i have three questions:
1. which version of the game are u playing?
2. are your copy of the game a original one?
3. which method u use to disable the anti-cheat?

**Comment by Teacyn** [comment]
Playing latest version of the game (1.16), steam version. For the anti-cheat, since I'm using ME2 that disables the anti-cheat automatically.

Still no luck on 0.5.4 unfortunately.

[souls_vision.log](https://github.com/user-attachments/files/18446736/souls_vision.log)

**Comment by samjviana** [comment]
it was brought to my attention that 0.3.3 is more stable. i don't know exactly why yet, but can you test it? it is available on nexus.

**Comment by Teacyn** [comment]
It would appear that 0.3.3 works just fine for me. 

![Image](https://github.com/user-attachments/assets/c1ab97d0-6943-4958-b67e-4702ad247757)

[souls_vision.log](https://github.com/user-attachments/files/18465522/souls_vision.log)

**Comment by Scotomas** [comment]
> It would appear that 0.3.3 works just fine for me. 
> 
> ![Image](https://github.com/user-attachments/assets/c1ab97d0-6943-4958-b67e-4702ad247757)
> 
> [souls_vision.log](https://github.com/user-attachments/files/18465522/souls_vision.log)

I'm trying to get this version to work for me. All I'm using is seamlesscoop. 

All you had to do was drag and drop the dll and sv_assets into your mods folder? 

It worked for me the first time but after relaunching the game. It crashes after the mod finishes loading

No overlays either

**Comment by samjviana** [comment]
I'll be closing this and centering all "Crash at startup" problems in a primary issue, please refer to #17
